spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_app
    username: alex
    password: password
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081